def mostrar_menu():
    print("\n" + "="*40)
    print("🎲 LANZADOR DE DADOS")
    print("="*40)
    print("1. Poker de dados")
    print("2. D&D")
    print("3. Salir")
    print("Elige una opción: ", end="")
def mostrar_menu_rol():
    print("\n" + "-"*40)
    print("⚔️  MULTITIRADA D&D")
    print("-"*40)
    print("1. d4   2. d6   3. d8")
    print("4. d10  5. d12  6. d20")
    print("7. d100")
    print("-"*40)
    print("L. LANZAR TODO")
    print("C. VACIAR CESTA")
    print("8. VOLVER")
    print("-"*40)